//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ButtonFunctions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ButtonFunctions() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlLibrary.Properties.ButtonFunctions", typeof(ButtonFunctions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будильник.
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;AlarmInfoScreen&apos;, native: true });.
        /// </summary>
        internal static string Alarm_function {
            get {
                return ResourceManager.GetString("Alarm_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки времени AOD.
        /// </summary>
        internal static string AOD {
            get {
                return ResourceManager.GetString("AOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_standbyModelScreen&apos;, native: true });.
        /// </summary>
        internal static string AOD_function {
            get {
                return ResourceManager.GetString("AOD_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки стиля AOD.
        /// </summary>
        internal static string AODStyle {
            get {
                return ResourceManager.GetString("AODStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_standbyHomeScreen&apos;, native: true });.
        /// </summary>
        internal static string AODStyle_function {
            get {
                return ResourceManager.GetString("AODStyle_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистика заряда *.
        /// </summary>
        internal static string BatteryManager {
            get {
                return ResourceManager.GetString("BatteryManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_batteryManagerScreen&apos;, native: true });.
        /// </summary>
        internal static string BatteryManager_function {
            get {
                return ResourceManager.GetString("BatteryManager_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дисплей.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_displayBrightScreen&apos;, native: true });.
        /// </summary>
        internal static string Display_function {
            get {
                return ResourceManager.GetString("Display_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не беспокоить.
        /// </summary>
        internal static string DND {
            get {
                return ResourceManager.GetString("DND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_dndScreen&apos;, native: true });.
        /// </summary>
        internal static string DND_function {
            get {
                return ResourceManager.GetString("DND_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск телефона.
        /// </summary>
        internal static string FindPhone {
            get {
                return ResourceManager.GetString("FindPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;FindPhoneScreen&apos;, native: true });.
        /// </summary>
        internal static string FindPhone_function {
            get {
                return ResourceManager.GetString("FindPhone_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пульс.
        /// </summary>
        internal static string HeartRete {
            get {
                return ResourceManager.GetString("HeartRete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;heart_app_Screen&apos;, native: true });.
        /// </summary>
        internal static string HeartRete_function {
            get {
                return ResourceManager.GetString("HeartRete_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Яркость.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_lightAdjustScreen&apos;, native: true });.
        /// </summary>
        internal static string Light_function {
            get {
                return ResourceManager.GetString("Light_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экономия заряда.
        /// </summary>
        internal static string LowBattery {
            get {
                return ResourceManager.GetString("LowBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;LowBatteryScreen&apos;, native: true });.
        /// </summary>
        internal static string LowBattery_function {
            get {
                return ResourceManager.GetString("LowBattery_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Женский календарь.
        /// </summary>
        internal static string Menstrual {
            get {
                return ResourceManager.GetString("Menstrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;menstrualAppScreen&apos;, native: true });.
        /// </summary>
        internal static string Menstrual_function {
            get {
                return ResourceManager.GetString("Menstrual_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измерение одним касанием.
        /// </summary>
        internal static string OneKey {
            get {
                return ResourceManager.GetString("OneKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;oneKeyAppScreen&apos;, native: true });.
        /// </summary>
        internal static string OneKey_function {
            get {
                return ResourceManager.GetString("OneKey_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PAI.
        /// </summary>
        internal static string PAI {
            get {
                return ResourceManager.GetString("PAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;PAI_app_Screen&apos;, native: true });.
        /// </summary>
        internal static string PAI_function {
            get {
                return ResourceManager.GetString("PAI_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Энергопотребление.
        /// </summary>
        internal static string PowerHint {
            get {
                return ResourceManager.GetString("PowerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;PowerSaveHintScreen&apos;, native: true });.
        /// </summary>
        internal static string PowerHint_function {
            get {
                return ResourceManager.GetString("PowerHint_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дыхание.
        /// </summary>
        internal static string Respiration {
            get {
                return ResourceManager.GetString("Respiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;RespirationwidgetScreen&apos;, native: true });.
        /// </summary>
        internal static string Respiration_function {
            get {
                return ResourceManager.GetString("Respiration_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выключить.
        /// </summary>
        internal static string ReStart {
            get {
                return ResourceManager.GetString("ReStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;HmReStartScreen&apos;, native: true });.
        /// </summary>
        internal static string ReStart_function {
            get {
                return ResourceManager.GetString("ReStart_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Простой циферблат.
        /// </summary>
        internal static string SaveMode {
            get {
                return ResourceManager.GetString("SaveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;PowerSaveModeScreen&apos;, native: true });.
        /// </summary>
        internal static string SaveMode_function {
            get {
                return ResourceManager.GetString("SaveMode_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Календарь.
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;ScheduleCalScreen&apos;, native: true });.
        /// </summary>
        internal static string Schedule_function {
            get {
                return ResourceManager.GetString("Schedule_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_homeScreen&apos;, native: true });.
        /// </summary>
        internal static string Settings_function {
            get {
                return ResourceManager.GetString("Settings_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сон.
        /// </summary>
        internal static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Sleep_HomeScreen&apos;, native: true });.
        /// </summary>
        internal static string Sleep_function {
            get {
                return ResourceManager.GetString("Sleep_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кислород.
        /// </summary>
        internal static string SPO2 {
            get {
                return ResourceManager.GetString("SPO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;spo_HomeScreen&apos;, native: true });.
        /// </summary>
        internal static string SPO2_function {
            get {
                return ResourceManager.GetString("SPO2_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последняя тренировка.
        /// </summary>
        internal static string Sport {
            get {
                return ResourceManager.GetString("Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;SportScreen&apos;, native: true });.
        /// </summary>
        internal static string Sport_function {
            get {
                return ResourceManager.GetString("Sport_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск тренировки.
        /// </summary>
        internal static string SportList {
            get {
                return ResourceManager.GetString("SportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;SportListScreen&apos;, native: true });.
        /// </summary>
        internal static string SportList_function {
            get {
                return ResourceManager.GetString("SportList_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Записи треноровок.
        /// </summary>
        internal static string SportRecord {
            get {
                return ResourceManager.GetString("SportRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;SportRecordListScreen&apos;, native: true });.
        /// </summary>
        internal static string SportRecord_function {
            get {
                return ResourceManager.GetString("SportRecord_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тренировочная нагрузка.
        /// </summary>
        internal static string SportStatus {
            get {
                return ResourceManager.GetString("SportStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;SportStatusScreen&apos;, native: true });.
        /// </summary>
        internal static string SportStatus_function {
            get {
                return ResourceManager.GetString("SportStatus_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаги.
        /// </summary>
        internal static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;activityAppScreen&apos;, native: true });.
        /// </summary>
        internal static string Steps_function {
            get {
                return ResourceManager.GetString("Steps_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стресс.
        /// </summary>
        internal static string Stress {
            get {
                return ResourceManager.GetString("Stress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;StressHomeScreen&apos;, native: true });.
        /// </summary>
        internal static string Stress_function {
            get {
                return ResourceManager.GetString("Stress_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Раздел &quot;Система&quot;.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_systemScreen&apos;, native: true });.
        /// </summary>
        internal static string System_function {
            get {
                return ResourceManager.GetString("System_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест.
        /// </summary>
        internal static string Test1 {
            get {
                return ResourceManager.GetString("Test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Test1Screen&apos;, native: true });.
        /// </summary>
        internal static string Test1_function {
            get {
                return ResourceManager.GetString("Test1_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест (простой).
        /// </summary>
        internal static string Test2 {
            get {
                return ResourceManager.GetString("Test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Test2Screen&apos;, native: true });.
        /// </summary>
        internal static string Test2_function {
            get {
                return ResourceManager.GetString("Test2_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать циферблат.
        /// </summary>
        internal static string WatchFace {
            get {
                return ResourceManager.GetString("WatchFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;WatchFaceScreen&apos;, native: true });.
        /// </summary>
        internal static string WatchFace_function {
            get {
                return ResourceManager.GetString("WatchFace_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мировое время.
        /// </summary>
        internal static string WorldClock {
            get {
                return ResourceManager.GetString("WorldClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;WorldClockScreen&apos;, native: true });.
        /// </summary>
        internal static string WorldClock_function {
            get {
                return ResourceManager.GetString("WorldClock_function", resourceCulture);
            }
        }
    }
}
