//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ButtonFunctions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ButtonFunctions() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlLibrary.Properties.ButtonFunctions", typeof(ButtonFunctions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будильник.
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;AlarmInfoScreen&apos;, native: true });.
        /// </summary>
        internal static string Alarm_function {
            get {
                return ResourceManager.GetString("Alarm_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки времени AOD.
        /// </summary>
        internal static string AOD {
            get {
                return ResourceManager.GetString("AOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_standbyModelScreen&apos;, native: true });.
        /// </summary>
        internal static string AOD_function {
            get {
                return ResourceManager.GetString("AOD_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки стиля AOD.
        /// </summary>
        internal static string AODStyle {
            get {
                return ResourceManager.GetString("AODStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_standbyHomeScreen&apos;, native: true });.
        /// </summary>
        internal static string AODStyle_function {
            get {
                return ResourceManager.GetString("AODStyle_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список программ.
        /// </summary>
        internal static string AppList {
            get {
                return ResourceManager.GetString("AppList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;AppListScreen&apos;, native: true });.
        /// </summary>
        internal static string AppList_function {
            get {
                return ResourceManager.GetString("AppList_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешения программ *.
        /// </summary>
        internal static string AppPermission {
            get {
                return ResourceManager.GetString("AppPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_permissionAppsScreen&apos;, native: true });.
        /// </summary>
        internal static string AppPermission_function {
            get {
                return ResourceManager.GetString("AppPermission_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Барометр.
        /// </summary>
        internal static string Baro {
            get {
                return ResourceManager.GetString("Baro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;BaroAltimeterScreen&apos;, native: true });.
        /// </summary>
        internal static string Baro_function {
            get {
                return ResourceManager.GetString("Baro_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистика использования *.
        /// </summary>
        internal static string BatteryManager {
            get {
                return ResourceManager.GetString("BatteryManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_batteryManagerScreen&apos;, native: true });.
        /// </summary>
        internal static string BatteryManager_function {
            get {
                return ResourceManager.GetString("BatteryManager_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состав тела *.
        /// </summary>
        internal static string BodyComposition {
            get {
                return ResourceManager.GetString("BodyComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;BodyCompositionResultScreen&apos;, native: true });.
        /// </summary>
        internal static string BodyComposition_function {
            get {
                return ResourceManager.GetString("BodyComposition_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление камерой.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;HidcameraScreen&apos;, native: true });.
        /// </summary>
        internal static string Camera_function {
            get {
                return ResourceManager.GetString("Camera_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карточка участника.
        /// </summary>
        internal static string ClubCards {
            get {
                return ResourceManager.GetString("ClubCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;ClubCardsScreen&apos;, native: true });.
        /// </summary>
        internal static string ClubCards_function {
            get {
                return ResourceManager.GetString("ClubCards_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компас.
        /// </summary>
        internal static string Compass {
            get {
                return ResourceManager.GetString("Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;CompassScreen&apos;, native: true });.
        /// </summary>
        internal static string Compass_function {
            get {
                return ResourceManager.GetString("Compass_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты *.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;PhoneContactsScreen&apos;, native: true });.
        /// </summary>
        internal static string Contacts_function {
            get {
                return ResourceManager.GetString("Contacts_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки шторки *.
        /// </summary>
        internal static string ControlCenter {
            get {
                return ResourceManager.GetString("ControlCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;ControlCenterEditScreen&apos;, native: true });.
        /// </summary>
        internal static string ControlCenter_function {
            get {
                return ResourceManager.GetString("ControlCenter_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обратный отсчет.
        /// </summary>
        internal static string CountDown {
            get {
                return ResourceManager.GetString("CountDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;CountdownAppScreen&apos;, native: true });.
        /// </summary>
        internal static string CountDown_function {
            get {
                return ResourceManager.GetString("CountDown_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номеронабиратель *.
        /// </summary>
        internal static string DialCall {
            get {
                return ResourceManager.GetString("DialCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;DialCallScreen&apos;, native: true });.
        /// </summary>
        internal static string DialCall_function {
            get {
                return ResourceManager.GetString("DialCall_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дисплей.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_displayBrightScreen&apos;, native: true });.
        /// </summary>
        internal static string Display_function {
            get {
                return ResourceManager.GetString("Display_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не беспокоить.
        /// </summary>
        internal static string DND {
            get {
                return ResourceManager.GetString("DND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_dndScreen&apos;, native: true });.
        /// </summary>
        internal static string DND_function {
            get {
                return ResourceManager.GetString("DND_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иконки программ.
        /// </summary>
        internal static string DragList {
            get {
                return ResourceManager.GetString("DragList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;DragListScreen&apos;, native: true });.
        /// </summary>
        internal static string DragList_function {
            get {
                return ResourceManager.GetString("DragList_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск телефона.
        /// </summary>
        internal static string FindPhone {
            get {
                return ResourceManager.GetString("FindPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;FindPhoneScreen&apos;, native: true });.
        /// </summary>
        internal static string FindPhone_function {
            get {
                return ResourceManager.GetString("FindPhone_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пульс.
        /// </summary>
        internal static string HeartRete {
            get {
                return ResourceManager.GetString("HeartRete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;heart_app_Screen&apos;, native: true });.
        /// </summary>
        internal static string HeartRete_function {
            get {
                return ResourceManager.GetString("HeartRete_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Яркость.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_lightAdjustScreen&apos;, native: true });.
        /// </summary>
        internal static string Light_function {
            get {
                return ResourceManager.GetString("Light_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Музыка (на часах) *.
        /// </summary>
        internal static string LocalMusic {
            get {
                return ResourceManager.GetString("LocalMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;LocalMusicScreen&apos;, native: true });.
        /// </summary>
        internal static string LocalMusic_function {
            get {
                return ResourceManager.GetString("LocalMusic_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экономия заряда.
        /// </summary>
        internal static string LowBattery {
            get {
                return ResourceManager.GetString("LowBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;LowBatteryScreen&apos;, native: true });.
        /// </summary>
        internal static string LowBattery_function {
            get {
                return ResourceManager.GetString("LowBattery_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Женский календарь.
        /// </summary>
        internal static string Menstrual {
            get {
                return ResourceManager.GetString("Menstrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;menstrualAppScreen&apos;, native: true });.
        /// </summary>
        internal static string Menstrual_function {
            get {
                return ResourceManager.GetString("Menstrual_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меню &quot;Ещё&quot; *.
        /// </summary>
        internal static string MoreList {
            get {
                return ResourceManager.GetString("MoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;MoreListScreen&apos;, native: true });.
        /// </summary>
        internal static string MoreList_function {
            get {
                return ResourceManager.GetString("MoreList_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Утренее приветствие *.
        /// </summary>
        internal static string MorningNews {
            get {
                return ResourceManager.GetString("MorningNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;MorningGreetingNewsScreen&apos;, native: true });.
        /// </summary>
        internal static string MorningNews_function {
            get {
                return ResourceManager.GetString("MorningNews_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мониторинг здоровья во сне *.
        /// </summary>
        internal static string NightMonitor {
            get {
                return ResourceManager.GetString("NightMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;oneKeyNightMonitorScreen&apos;, native: true });.
        /// </summary>
        internal static string NightMonitor_function {
            get {
                return ResourceManager.GetString("NightMonitor_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измерение одним касанием.
        /// </summary>
        internal static string OneKey {
            get {
                return ResourceManager.GetString("OneKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;oneKeyAppScreen&apos;, native: true });.
        /// </summary>
        internal static string OneKey_function {
            get {
                return ResourceManager.GetString("OneKey_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PAI.
        /// </summary>
        internal static string PAI {
            get {
                return ResourceManager.GetString("PAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;PAI_app_Screen&apos;, native: true });.
        /// </summary>
        internal static string PAI_function {
            get {
                return ResourceManager.GetString("PAI_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон *.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;PhoneHomeScreen&apos;, native: true });.
        /// </summary>
        internal static string Phone_function {
            get {
                return ResourceManager.GetString("Phone_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Музыка (на телефоне).
        /// </summary>
        internal static string PhoneMusic {
            get {
                return ResourceManager.GetString("PhoneMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;PhoneMusicCtrlScreen&apos;, native: true });.
        /// </summary>
        internal static string PhoneMusic_function {
            get {
                return ResourceManager.GetString("PhoneMusic_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Энергопотребление.
        /// </summary>
        internal static string PowerHint {
            get {
                return ResourceManager.GetString("PowerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;PowerSaveHintScreen&apos;, native: true });.
        /// </summary>
        internal static string PowerHint_function {
            get {
                return ResourceManager.GetString("PowerHint_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готовность *.
        /// </summary>
        internal static string Readiness {
            get {
                return ResourceManager.GetString("Readiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;readinessAppScreen&apos;, native: true });.
        /// </summary>
        internal static string Readiness_function {
            get {
                return ResourceManager.GetString("Readiness_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последние вызовы *.
        /// </summary>
        internal static string RecentCall {
            get {
                return ResourceManager.GetString("RecentCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;PhoneRecentCallScreen&apos;, native: true });.
        /// </summary>
        internal static string RecentCall_function {
            get {
                return ResourceManager.GetString("RecentCall_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дыхание.
        /// </summary>
        internal static string Respiration {
            get {
                return ResourceManager.GetString("Respiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;RespirationwidgetScreen&apos;, native: true });.
        /// </summary>
        internal static string Respiration_function {
            get {
                return ResourceManager.GetString("Respiration_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дыхание *.
        /// </summary>
        internal static string RespirationControl {
            get {
                return ResourceManager.GetString("RespirationControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;RespirationControlScreen&apos;, native: true });.
        /// </summary>
        internal static string RespirationControl_function {
            get {
                return ResourceManager.GetString("RespirationControl_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выключить.
        /// </summary>
        internal static string ReStart {
            get {
                return ResourceManager.GetString("ReStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;HmReStartScreen&apos;, native: true });.
        /// </summary>
        internal static string ReStart_function {
            get {
                return ResourceManager.GetString("ReStart_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Простой циферблат.
        /// </summary>
        internal static string SaveMode {
            get {
                return ResourceManager.GetString("SaveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;PowerSaveModeScreen&apos;, native: true });.
        /// </summary>
        internal static string SaveMode_function {
            get {
                return ResourceManager.GetString("SaveMode_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Календарь.
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;ScheduleCalScreen&apos;, native: true });.
        /// </summary>
        internal static string Schedule_function {
            get {
                return ResourceManager.GetString("Schedule_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расписание.
        /// </summary>
        internal static string ScheduleList {
            get {
                return ResourceManager.GetString("ScheduleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;ScheduleListScreen&apos;, native: true });.
        /// </summary>
        internal static string ScheduleList_function {
            get {
                return ResourceManager.GetString("ScheduleList_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_homeScreen&apos;, native: true });.
        /// </summary>
        internal static string Settings_function {
            get {
                return ResourceManager.GetString("Settings_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сон.
        /// </summary>
        internal static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Sleep_HomeScreen&apos;, native: true });.
        /// </summary>
        internal static string Sleep_function {
            get {
                return ResourceManager.GetString("Sleep_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SpO2 (Кислород).
        /// </summary>
        internal static string SPO2 {
            get {
                return ResourceManager.GetString("SPO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;spo_HomeScreen&apos;, native: true });.
        /// </summary>
        internal static string SPO2_function {
            get {
                return ResourceManager.GetString("SPO2_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последняя тренировка.
        /// </summary>
        internal static string Sport {
            get {
                return ResourceManager.GetString("Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;SportScreen&apos;, native: true });.
        /// </summary>
        internal static string Sport_function {
            get {
                return ResourceManager.GetString("Sport_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск тренировки.
        /// </summary>
        internal static string SportList {
            get {
                return ResourceManager.GetString("SportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;SportListScreen&apos;, native: true });.
        /// </summary>
        internal static string SportList_function {
            get {
                return ResourceManager.GetString("SportList_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Записи треноровок.
        /// </summary>
        internal static string SportRecord {
            get {
                return ResourceManager.GetString("SportRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;SportRecordListScreen&apos;, native: true });.
        /// </summary>
        internal static string SportRecord_function {
            get {
                return ResourceManager.GetString("SportRecord_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тренировочная нагрузка.
        /// </summary>
        internal static string SportStatus {
            get {
                return ResourceManager.GetString("SportStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;SportStatusScreen&apos;, native: true });.
        /// </summary>
        internal static string SportStatus_function {
            get {
                return ResourceManager.GetString("SportStatus_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаги.
        /// </summary>
        internal static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;activityAppScreen&apos;, native: true });.
        /// </summary>
        internal static string Steps_function {
            get {
                return ResourceManager.GetString("Steps_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Секундомер.
        /// </summary>
        internal static string StopWatch {
            get {
                return ResourceManager.GetString("StopWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;StopWatchScreen&apos;, native: true });.
        /// </summary>
        internal static string StopWatch_function {
            get {
                return ResourceManager.GetString("StopWatch_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стресс.
        /// </summary>
        internal static string Stress {
            get {
                return ResourceManager.GetString("Stress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;StressHomeScreen&apos;, native: true });.
        /// </summary>
        internal static string Stress_function {
            get {
                return ResourceManager.GetString("Stress_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восход/закат.
        /// </summary>
        internal static string Sunset {
            get {
                return ResourceManager.GetString("Sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;TideScreen&apos;, native: true });.
        /// </summary>
        internal static string Sunset_function {
            get {
                return ResourceManager.GetString("Sunset_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Раздел &quot;Система&quot;.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Settings_systemScreen&apos;, native: true });.
        /// </summary>
        internal static string System_function {
            get {
                return ResourceManager.GetString("System_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест.
        /// </summary>
        internal static string Test1 {
            get {
                return ResourceManager.GetString("Test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Test1Screen&apos;, native: true });.
        /// </summary>
        internal static string Test1_function {
            get {
                return ResourceManager.GetString("Test1_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест (простой).
        /// </summary>
        internal static string Test2 {
            get {
                return ResourceManager.GetString("Test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;Test2Screen&apos;, native: true });.
        /// </summary>
        internal static string Test2_function {
            get {
                return ResourceManager.GetString("Test2_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таймер.
        /// </summary>
        internal static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;TomatoMainScreen&apos;, native: true });.
        /// </summary>
        internal static string Timer_function {
            get {
                return ResourceManager.GetString("Timer_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список дел.
        /// </summary>
        internal static string ToDoList {
            get {
                return ResourceManager.GetString("ToDoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;todoListScreen&apos;, native: true });.
        /// </summary>
        internal static string ToDoList_function {
            get {
                return ResourceManager.GetString("ToDoList_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Голосовая заметка.
        /// </summary>
        internal static string VoiceMemo {
            get {
                return ResourceManager.GetString("VoiceMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;VoiceMemoScreen&apos;, native: true });.
        /// </summary>
        internal static string VoiceMemo_function {
            get {
                return ResourceManager.GetString("VoiceMemo_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать циферблат.
        /// </summary>
        internal static string WatchFace {
            get {
                return ResourceManager.GetString("WatchFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;WatchFaceScreen&apos;, native: true });.
        /// </summary>
        internal static string WatchFace_function {
            get {
                return ResourceManager.GetString("WatchFace_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Погода.
        /// </summary>
        internal static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;WeatherScreen&apos;, native: true });.
        /// </summary>
        internal static string Weather_function {
            get {
                return ResourceManager.GetString("Weather_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активность за неделю *.
        /// </summary>
        internal static string WeekActivity {
            get {
                return ResourceManager.GetString("WeekActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;activityWeekShowScreen&apos;, native: true });.
        /// </summary>
        internal static string WeekActivity_function {
            get {
                return ResourceManager.GetString("WeekActivity_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки виджетов *.
        /// </summary>
        internal static string WidgetEdit {
            get {
                return ResourceManager.GetString("WidgetEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;WidgetEditScreen&apos;, native: true });.
        /// </summary>
        internal static string WidgetEdit_function {
            get {
                return ResourceManager.GetString("WidgetEdit_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мировое время.
        /// </summary>
        internal static string WorldClock {
            get {
                return ResourceManager.GetString("WorldClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hmApp.startApp({url: &apos;WorldClockScreen&apos;, native: true });.
        /// </summary>
        internal static string WorldClock_function {
            get {
                return ResourceManager.GetString("WorldClock_function", resourceCulture);
            }
        }
    }
}
