//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watch_Face_Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ElementsString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ElementsString() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Watch_Face_Editor.Properties.ElementsString", typeof(ElementsString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такой элемент уже есть.
        /// </summary>
        internal static string ElementExists {
            get {
                return ResourceManager.GetString("ElementExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Барометр.
        /// </summary>
        internal static string TypeAltimeter {
            get {
                return ResourceManager.GetString("TypeAltimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заряд.
        /// </summary>
        internal static string TypeBattery {
            get {
                return ResourceManager.GetString("TypeBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Калории.
        /// </summary>
        internal static string TypeCalories {
            get {
                return ResourceManager.GetString("TypeCalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число.
        /// </summary>
        internal static string TypeDay {
            get {
                return ResourceManager.GetString("TypeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дистанция.
        /// </summary>
        internal static string TypeDistance {
            get {
                return ResourceManager.GetString("TypeDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жиросжигание.
        /// </summary>
        internal static string TypeFatBurning {
            get {
                return ResourceManager.GetString("TypeFatBurning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пульс.
        /// </summary>
        internal static string TypeHeart {
            get {
                return ResourceManager.GetString("TypeHeart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Влажность.
        /// </summary>
        internal static string TypeHumidity {
            get {
                return ResourceManager.GetString("TypeHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Месяц.
        /// </summary>
        internal static string TypeMonth {
            get {
                return ResourceManager.GetString("TypeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фазы луны.
        /// </summary>
        internal static string TypeMoon {
            get {
                return ResourceManager.GetString("TypeMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Батарея.
        /// </summary>
        internal static string TypeNameBattery {
            get {
                return ResourceManager.GetString("TypeNameBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сожжено.
        /// </summary>
        internal static string TypeNameCalories {
            get {
                return ResourceManager.GetString("TypeNameCalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        internal static string TypeNameDate {
            get {
                return ResourceManager.GetString("TypeNameDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расстояние.
        /// </summary>
        internal static string TypeNameDistance {
            get {
                return ResourceManager.GetString("TypeNameDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жиросжигание.
        /// </summary>
        internal static string TypeNameFatBurning {
            get {
                return ResourceManager.GetString("TypeNameFatBurning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сердцебиение.
        /// </summary>
        internal static string TypeNameHeart {
            get {
                return ResourceManager.GetString("TypeNameHeart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PAI сегодня.
        /// </summary>
        internal static string TypeNamePAI {
            get {
                return ResourceManager.GetString("TypeNamePAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кислород в крови.
        /// </summary>
        internal static string TypeNameSpO2 {
            get {
                return ResourceManager.GetString("TypeNameSpO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стою.
        /// </summary>
        internal static string TypeNameStand {
            get {
                return ResourceManager.GetString("TypeNameStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К-во шагов.
        /// </summary>
        internal static string TypeNameStep {
            get {
                return ResourceManager.GetString("TypeNameStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стресс.
        /// </summary>
        internal static string TypeNameStress {
            get {
                return ResourceManager.GetString("TypeNameStress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PAI.
        /// </summary>
        internal static string TypePAI {
            get {
                return ResourceManager.GetString("TypePAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кислород в крови.
        /// </summary>
        internal static string TypeSpO2 {
            get {
                return ResourceManager.GetString("TypeSpO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разминка.
        /// </summary>
        internal static string TypeStand {
            get {
                return ResourceManager.GetString("TypeStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаги.
        /// </summary>
        internal static string TypeSteps {
            get {
                return ResourceManager.GetString("TypeSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стресс.
        /// </summary>
        internal static string TypeStress {
            get {
                return ResourceManager.GetString("TypeStress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восход / закат.
        /// </summary>
        internal static string TypeSunrise {
            get {
                return ResourceManager.GetString("TypeSunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УФ индекс.
        /// </summary>
        internal static string TypeUVIndex {
            get {
                return ResourceManager.GetString("TypeUVIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Погода.
        /// </summary>
        internal static string TypeWeather {
            get {
                return ResourceManager.GetString("TypeWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на День недели.
        /// </summary>
        internal static string TypeWeek {
            get {
                return ResourceManager.GetString("TypeWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сила ветра.
        /// </summary>
        internal static string TypeWind {
            get {
                return ResourceManager.GetString("TypeWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Год.
        /// </summary>
        internal static string TypeYear {
            get {
                return ResourceManager.GetString("TypeYear", resourceCulture);
            }
        }
    }
}
