//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watch_Face_Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Watch_Face_Editor.Properties.FormStrings", typeof(FormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a dial settings file.
        /// </summary>
        internal static string Dialog_Title_Dial_Settings {
            get {
                return ResourceManager.GetString("Dialog_Title_Dial_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select image files.
        /// </summary>
        internal static string Dialog_Title_Image {
            get {
                return ResourceManager.GetString("Dialog_Title_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creating a new project.
        /// </summary>
        internal static string Dialog_Title_New_Project {
            get {
                return ResourceManager.GetString("Dialog_Title_New_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selecting a watch face settings file.
        /// </summary>
        internal static string Dialog_Title_Open {
            get {
                return ResourceManager.GetString("Dialog_Title_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selecting a watch image file.
        /// </summary>
        internal static string Dialog_Title_WatchSkin {
            get {
                return ResourceManager.GetString("Dialog_Title_WatchSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активности.
        /// </summary>
        internal static string Elemet_Activity {
            get {
                return ResourceManager.GetString("Elemet_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Атмосфера.
        /// </summary>
        internal static string Elemet_Air {
            get {
                return ResourceManager.GetString("Elemet_Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        internal static string Elemet_Date {
            get {
                return ResourceManager.GetString("Elemet_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Система.
        /// </summary>
        internal static string Elemet_System {
            get {
                return ResourceManager.GetString("Elemet_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время.
        /// </summary>
        internal static string Elemet_Time {
            get {
                return ResourceManager.GetString("Elemet_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GIF Files (*.gif)|*.gif.
        /// </summary>
        internal static string FilterGif {
            get {
                return ResourceManager.GetString("FilterGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Json files (*.json) | *.json.
        /// </summary>
        internal static string FilterJson {
            get {
                return ResourceManager.GetString("FilterJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PNG Files (*.png)|*.png.
        /// </summary>
        internal static string FilterPng {
            get {
                return ResourceManager.GetString("FilterPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preview.
        /// </summary>
        internal static string Form_Preview {
            get {
                return ResourceManager.GetString("Form_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preview [X =.
        /// </summary>
        internal static string Form_PreviewX {
            get {
                return ResourceManager.GetString("Form_PreviewX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Coordinates copied.
        /// </summary>
        internal static string Message_CopyCoord {
            get {
                return ResourceManager.GetString("Message_CopyCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string Message_Error_Caption {
            get {
                return ResourceManager.GetString("Message_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to open image:.
        /// </summary>
        internal static string Message_Error_Image_Text1 {
            get {
                return ResourceManager.GetString("Message_Error_Image_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на . You do not have permission to read the file, or the image is damaged..
        /// </summary>
        internal static string Message_Error_Image_Text2 {
            get {
                return ResourceManager.GetString("Message_Error_Image_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid JSON file..
        /// </summary>
        internal static string Message_JsonError_Text {
            get {
                return ResourceManager.GetString("Message_JsonError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reboot.
        /// </summary>
        internal static string Message_Restart_Caption {
            get {
                return ResourceManager.GetString("Message_Restart_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To apply the settings, you must restart the program..
        /// </summary>
        internal static string Message_Restart_Text1 {
            get {
                return ResourceManager.GetString("Message_Restart_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart the program?.
        /// </summary>
        internal static string Message_Restart_Text2 {
            get {
                return ResourceManager.GetString("Message_Restart_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save the project.
        /// </summary>
        internal static string Message_Save_JSON_Modified_Caption {
            get {
                return ResourceManager.GetString("Message_Save_JSON_Modified_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do You want save changes of project .
        /// </summary>
        internal static string Message_Save_JSON_Modified_Text1 {
            get {
                return ResourceManager.GetString("Message_Save_JSON_Modified_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ?.
        /// </summary>
        internal static string Message_Save_JSON_Modified_Text2 {
            get {
                return ResourceManager.GetString("Message_Save_JSON_Modified_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The current project has not yet been saved. Do you want to save it?.
        /// </summary>
        internal static string Message_Save_new_JSON {
            get {
                return ResourceManager.GetString("Message_Save_new_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В этой папке уже существует папка с изображениями..
        /// </summary>
        internal static string Message_Warning_Assets_Exist1 {
            get {
                return ResourceManager.GetString("Message_Warning_Assets_Exist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рекомендуется создавать проект в отдельной папке..
        /// </summary>
        internal static string Message_Warning_Assets_Exist2 {
            get {
                return ResourceManager.GetString("Message_Warning_Assets_Exist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать проект в выбраной папке?.
        /// </summary>
        internal static string Message_Warning_Assets_Exist3 {
            get {
                return ResourceManager.GetString("Message_Warning_Assets_Exist3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        internal static string Message_Warning_Caption {
            get {
                return ResourceManager.GetString("Message_Warning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В проекте уже существует изображение:.
        /// </summary>
        internal static string Message_Warning_Image_Exist1 {
            get {
                return ResourceManager.GetString("Message_Warning_Image_Exist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заменить его новым изображением?.
        /// </summary>
        internal static string Message_Warning_Image_Exist2 {
            get {
                return ResourceManager.GetString("Message_Warning_Image_Exist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        internal static string Message_Warning_Information {
            get {
                return ResourceManager.GetString("Message_Warning_Information", resourceCulture);
            }
        }
    }
}
