//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watch_Face_Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Watch_Face_Editor.Properties.FormStrings", typeof(FormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файл настроек циферблата.
        /// </summary>
        internal static string Dialog_Title_Dial_Settings {
            get {
                return ResourceManager.GetString("Dialog_Title_Dial_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файлы изображений.
        /// </summary>
        internal static string Dialog_Title_Image {
            get {
                return ResourceManager.GetString("Dialog_Title_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание нового проекта.
        /// </summary>
        internal static string Dialog_Title_New_Project {
            get {
                return ResourceManager.GetString("Dialog_Title_New_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор файла настроек предпросмотра.
        /// </summary>
        internal static string Dialog_Title_PreviewStates {
            get {
                return ResourceManager.GetString("Dialog_Title_PreviewStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить анимированный предпросмотр.
        /// </summary>
        internal static string Dialog_Title_SaveGIF {
            get {
                return ResourceManager.GetString("Dialog_Title_SaveGIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить предпросмотр.
        /// </summary>
        internal static string Dialog_Title_SavePNG {
            get {
                return ResourceManager.GetString("Dialog_Title_SavePNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор файла циферблата.
        /// </summary>
        internal static string Dialog_Title_Unpack {
            get {
                return ResourceManager.GetString("Dialog_Title_Unpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор файла изображения часов.
        /// </summary>
        internal static string Dialog_Title_WatchSkin {
            get {
                return ResourceManager.GetString("Dialog_Title_WatchSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активности.
        /// </summary>
        internal static string Elemet_Activity {
            get {
                return ResourceManager.GetString("Elemet_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Атмосфера.
        /// </summary>
        internal static string Elemet_Air {
            get {
                return ResourceManager.GetString("Elemet_Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        internal static string Elemet_Date {
            get {
                return ResourceManager.GetString("Elemet_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Система.
        /// </summary>
        internal static string Elemet_System {
            get {
                return ResourceManager.GetString("Elemet_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время.
        /// </summary>
        internal static string Elemet_Time {
            get {
                return ResourceManager.GetString("Elemet_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GIF файлы (*.gif)|*.gif.
        /// </summary>
        internal static string FilterGif {
            get {
                return ResourceManager.GetString("FilterGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Json файлы (*.json) | *.json.
        /// </summary>
        internal static string FilterJson {
            get {
                return ResourceManager.GetString("FilterJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PNG файлы (*.png)|*.png.
        /// </summary>
        internal static string FilterPng {
            get {
                return ResourceManager.GetString("FilterPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zip файл циферблата (*.zip) | *.zip.
        /// </summary>
        internal static string FilterZip {
            get {
                return ResourceManager.GetString("FilterZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следовать за часами.
        /// </summary>
        internal static string FollowMinute {
            get {
                return ResourceManager.GetString("FollowMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следовать за минутами.
        /// </summary>
        internal static string FollowSecond {
            get {
                return ResourceManager.GetString("FollowSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предпросмотр.
        /// </summary>
        internal static string Form_Preview {
            get {
                return ResourceManager.GetString("Form_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предпросмотр [X =.
        /// </summary>
        internal static string Form_PreviewX {
            get {
                return ResourceManager.GetString("Form_PreviewX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете добавлять анимацию на экран AOD..
        /// </summary>
        internal static string Message_AnimationAOD_Text {
            get {
                return ResourceManager.GetString("Message_AnimationAOD_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый циферблат создан..
        /// </summary>
        internal static string Message_ConvertingCompleted_Text {
            get {
                return ResourceManager.GetString("Message_ConvertingCompleted_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Координаты скопированны.
        /// </summary>
        internal static string Message_CopyCoord {
            get {
                return ResourceManager.GetString("Message_CopyCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление.
        /// </summary>
        internal static string Message_Delet_Caption {
            get {
                return ResourceManager.GetString("Message_Delet_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите безвозвратно удалить файл &quot;.
        /// </summary>
        internal static string Message_Delet_Text1 {
            get {
                return ResourceManager.GetString("Message_Delet_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите безвозвратно удалить файлы:.
        /// </summary>
        internal static string Message_Delet_Text11 {
            get {
                return ResourceManager.GetString("Message_Delet_Text11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;?.
        /// </summary>
        internal static string Message_Delet_Text2 {
            get {
                return ResourceManager.GetString("Message_Delet_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ?.
        /// </summary>
        internal static string Message_Delet_Text21 {
            get {
                return ResourceManager.GetString("Message_Delet_Text21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете добавлять настраиваемые элементы на экран AOD..
        /// </summary>
        internal static string Message_EditableElementsAOD_Text {
            get {
                return ResourceManager.GetString("Message_EditableElementsAOD_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете добавлять настраиваемые стрелки на экран AOD..
        /// </summary>
        internal static string Message_EditablePointerAOD_Text {
            get {
                return ResourceManager.GetString("Message_EditablePointerAOD_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string Message_Error_Caption {
            get {
                return ResourceManager.GetString("Message_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно открыть изображение:.
        /// </summary>
        internal static string Message_Error_Image_Text1 {
            get {
                return ResourceManager.GetString("Message_Error_Image_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на . У Вас нет прав на чтение файла, или изображение повреждено..
        /// </summary>
        internal static string Message_Error_Image_Text2 {
            get {
                return ResourceManager.GetString("Message_Error_Image_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось распознать структуру циферблата.
        /// </summary>
        internal static string Message_ErrorReadJS {
            get {
                return ResourceManager.GetString("Message_ErrorReadJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти к файлу.
        /// </summary>
        internal static string Message_GoToFile_Caption {
            get {
                return ResourceManager.GetString("Message_GoToFile_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти к файлу?.
        /// </summary>
        internal static string Message_GoToFile_Text {
            get {
                return ResourceManager.GetString("Message_GoToFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение не должно быть монохромным и должно быть в формате 32bit.
        /// </summary>
        internal static string Message_Image32bit {
            get {
                return ResourceManager.GetString("Message_Image32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранные изображения выходят за диапазон имеющихся изображений..
        /// </summary>
        internal static string Message_ImageCount_Error {
            get {
                return ResourceManager.GetString("Message_ImageCount_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка конвертации изображения.
        /// </summary>
        internal static string Message_ImageFix_Error {
            get {
                return ResourceManager.GetString("Message_ImageFix_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный JSON file..
        /// </summary>
        internal static string Message_JsonError_Text {
            get {
                return ResourceManager.GetString("Message_JsonError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения JSON файла..
        /// </summary>
        internal static string Message_JsonReadError_Text {
            get {
                return ResourceManager.GetString("Message_JsonReadError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка настроек предпросмотра.
        /// </summary>
        internal static string Message_LoadPreviewStates_Caption {
            get {
                return ResourceManager.GetString("Message_LoadPreviewStates_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить имеющийся файл с набором параметров предпросмотра PreviewStates.json?.
        /// </summary>
        internal static string Message_LoadPreviewStates_Text {
            get {
                return ResourceManager.GetString("Message_LoadPreviewStates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезагрузка.
        /// </summary>
        internal static string Message_Restart_Caption {
            get {
                return ResourceManager.GetString("Message_Restart_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для применения настроек необходимо перезагрузить программу..
        /// </summary>
        internal static string Message_Restart_Text1 {
            get {
                return ResourceManager.GetString("Message_Restart_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезапустить программу?.
        /// </summary>
        internal static string Message_Restart_Text2 {
            get {
                return ResourceManager.GetString("Message_Restart_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение проекта.
        /// </summary>
        internal static string Message_Save_JSON_Modified_Caption {
            get {
                return ResourceManager.GetString("Message_Save_JSON_Modified_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы хотите сохранить изменения в проекте &quot;.
        /// </summary>
        internal static string Message_Save_JSON_Modified_Text1 {
            get {
                return ResourceManager.GetString("Message_Save_JSON_Modified_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;?.
        /// </summary>
        internal static string Message_Save_JSON_Modified_Text2 {
            get {
                return ResourceManager.GetString("Message_Save_JSON_Modified_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий проект еще не сохранен. Вы хотите сохранить его?.
        /// </summary>
        internal static string Message_Save_new_JSON {
            get {
                return ResourceManager.GetString("Message_Save_new_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для сохранения предустановленных параметром установите хотябы в одном поле &quot;Калории&quot; значение отличное от &quot;1234&quot;..
        /// </summary>
        internal static string Message_SaveOnly1234_Text {
            get {
                return ResourceManager.GetString("Message_SaveOnly1234_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете добавлять ярлыки на экран AOD..
        /// </summary>
        internal static string Message_ShortcutsAOD_Text {
            get {
                return ResourceManager.GetString("Message_ShortcutsAOD_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В этой папке уже существует папка с изображениями..
        /// </summary>
        internal static string Message_Warning_Assets_Exist1 {
            get {
                return ResourceManager.GetString("Message_Warning_Assets_Exist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рекомендуется создавать проект в отдельной папке..
        /// </summary>
        internal static string Message_Warning_Assets_Exist2 {
            get {
                return ResourceManager.GetString("Message_Warning_Assets_Exist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать проект в выбраной папке?.
        /// </summary>
        internal static string Message_Warning_Assets_Exist3 {
            get {
                return ResourceManager.GetString("Message_Warning_Assets_Exist3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        internal static string Message_Warning_Caption {
            get {
                return ResourceManager.GetString("Message_Warning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В проекте уже существует изображение:.
        /// </summary>
        internal static string Message_Warning_Image_Exist1 {
            get {
                return ResourceManager.GetString("Message_Warning_Image_Exist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заменить его новым изображением?.
        /// </summary>
        internal static string Message_Warning_Image_Exist2 {
            get {
                return ResourceManager.GetString("Message_Warning_Image_Exist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string Message_Warning_Information {
            get {
                return ResourceManager.GetString("Message_Warning_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каталог .
        /// </summary>
        internal static string Message_WarningConverting_Text1 {
            get {
                return ResourceManager.GetString("Message_WarningConverting_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  уже существует. Заменить?.
        /// </summary>
        internal static string Message_WarningConverting_Text2 {
            get {
                return ResourceManager.GetString("Message_WarningConverting_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размеры изображения для Preview отличаются от стандартных..
        /// </summary>
        internal static string Message_WarningPreview_Text1 {
            get {
                return ResourceManager.GetString("Message_WarningPreview_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использовать существующие размеры?.
        /// </summary>
        internal static string Message_WarningPreview_Text2 {
            get {
                return ResourceManager.GetString("Message_WarningPreview_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат исходного изображения.
        /// </summary>
        internal static string Message_Wrong_Original_Image {
            get {
                return ResourceManager.GetString("Message_Wrong_Original_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось создать изображение предпросмотра. Возможно такое изображение уже имеется..
        /// </summary>
        internal static string Message_Wrong_Preview_Exists {
            get {
                return ResourceManager.GetString("Message_Wrong_Preview_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фон .
        /// </summary>
        internal static string Tip_Background {
            get {
                return ResourceManager.GetString("Tip_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стрелки .
        /// </summary>
        internal static string Tip_Pointer {
            get {
                return ResourceManager.GetString("Tip_Pointer", resourceCulture);
            }
        }
    }
}
