//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watch_Face_Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Watch_Face_Editor.Properties.FormStrings", typeof(FormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл шрифта (*.ttf) | *.ttf.
        /// </summary>
        internal static string Dialog_FontFilter {
            get {
                return ResourceManager.GetString("Dialog_FontFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файл настроек циферблата.
        /// </summary>
        internal static string Dialog_Title_Dial_Settings {
            get {
                return ResourceManager.GetString("Dialog_Title_Dial_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файл шрифта.
        /// </summary>
        internal static string Dialog_Title_Font_Add {
            get {
                return ResourceManager.GetString("Dialog_Title_Font_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файлы изображений.
        /// </summary>
        internal static string Dialog_Title_Image {
            get {
                return ResourceManager.GetString("Dialog_Title_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание нового проекта.
        /// </summary>
        internal static string Dialog_Title_New_Project {
            get {
                return ResourceManager.GetString("Dialog_Title_New_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор файла настроек предпросмотра.
        /// </summary>
        internal static string Dialog_Title_PreviewStates {
            get {
                return ResourceManager.GetString("Dialog_Title_PreviewStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить проект как....
        /// </summary>
        internal static string Dialog_Title_Save_As {
            get {
                return ResourceManager.GetString("Dialog_Title_Save_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить анимированный предпросмотр.
        /// </summary>
        internal static string Dialog_Title_SaveGIF {
            get {
                return ResourceManager.GetString("Dialog_Title_SaveGIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить предпросмотр.
        /// </summary>
        internal static string Dialog_Title_SavePNG {
            get {
                return ResourceManager.GetString("Dialog_Title_SavePNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить QR-код.
        /// </summary>
        internal static string Dialog_Title_SaveQR {
            get {
                return ResourceManager.GetString("Dialog_Title_SaveQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор файла циферблата.
        /// </summary>
        internal static string Dialog_Title_Unpack {
            get {
                return ResourceManager.GetString("Dialog_Title_Unpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор файла изображения часов.
        /// </summary>
        internal static string Dialog_Title_WatchSkin {
            get {
                return ResourceManager.GetString("Dialog_Title_WatchSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активности.
        /// </summary>
        internal static string Elemet_Activity {
            get {
                return ResourceManager.GetString("Elemet_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Атмосфера.
        /// </summary>
        internal static string Elemet_Air {
            get {
                return ResourceManager.GetString("Elemet_Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        internal static string Elemet_Date {
            get {
                return ResourceManager.GetString("Elemet_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Система.
        /// </summary>
        internal static string Elemet_System {
            get {
                return ResourceManager.GetString("Elemet_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время.
        /// </summary>
        internal static string Elemet_Time {
            get {
                return ResourceManager.GetString("Elemet_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Занято места.
        /// </summary>
        internal static string FilePost_info_storage_used {
            get {
                return ResourceManager.GetString("FilePost_info_storage_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузок за месяц.
        /// </summary>
        internal static string FilePost_info_uploads_month {
            get {
                return ResourceManager.GetString("FilePost_info_uploads_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GIF файлы (*.gif)|*.gif.
        /// </summary>
        internal static string FilterGif {
            get {
                return ResourceManager.GetString("FilterGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Json файлы (*.json)|*.json.
        /// </summary>
        internal static string FilterJson {
            get {
                return ResourceManager.GetString("FilterJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PNG файлы (*.png)|*.png.
        /// </summary>
        internal static string FilterPng {
            get {
                return ResourceManager.GetString("FilterPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zip файл циферблата (*.zip)|*.zip.
        /// </summary>
        internal static string FilterZip {
            get {
                return ResourceManager.GetString("FilterZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл циферблата (*.zip; *.zpk)|*.zip; *.zpk.
        /// </summary>
        internal static string FilterZipZpk {
            get {
                return ResourceManager.GetString("FilterZipZpk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл циферблата (*.zpk)|*.zpk.
        /// </summary>
        internal static string FilterZpk {
            get {
                return ResourceManager.GetString("FilterZpk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следовать за часами.
        /// </summary>
        internal static string FollowMinute {
            get {
                return ResourceManager.GetString("FollowMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следовать за минутами.
        /// </summary>
        internal static string FollowSecond {
            get {
                return ResourceManager.GetString("FollowSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предпросмотр.
        /// </summary>
        internal static string Form_Preview {
            get {
                return ResourceManager.GetString("Form_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предпросмотр [X =.
        /// </summary>
        internal static string Form_PreviewX {
            get {
                return ResourceManager.GetString("Form_PreviewX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить информацию.
        /// </summary>
        internal static string FormName_EditInformation {
            get {
                return ResourceManager.GetString("FormName_EditInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка проверки авторизации.
        /// </summary>
        internal static string GitHub_AuthError {
            get {
                return ResourceManager.GetString("GitHub_AuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка существования репозитория....
        /// </summary>
        internal static string GitHub_CheckingRepository {
            get {
                return ResourceManager.GetString("GitHub_CheckingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка учетных данных GitHub....
        /// </summary>
        internal static string GitHub_CheckingToken {
            get {
                return ResourceManager.GetString("GitHub_CheckingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлен новый файл.
        /// </summary>
        internal static string GitHub_FileAdded {
            get {
                return ResourceManager.GetString("GitHub_FileAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переданный GitHub токен недействителен (ошибка 401 Unauthorized)..
        /// </summary>
        internal static string GitHub_InvalidToken {
            get {
                return ResourceManager.GetString("GitHub_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подготовка к запуску....
        /// </summary>
        internal static string GitHub_PreparingForLaunch {
            get {
                return ResourceManager.GetString("GitHub_PreparingForLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при проверке репозитория.
        /// </summary>
        internal static string GitHub_RepositoryCheckError {
            get {
                return ResourceManager.GetString("GitHub_RepositoryCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Репозиторий.
        /// </summary>
        internal static string GitHub_RepositoryNotFound1 {
            get {
                return ResourceManager.GetString("GitHub_RepositoryNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не найден или к нему нет доступа..
        /// </summary>
        internal static string GitHub_RepositoryNotFound2 {
            get {
                return ResourceManager.GetString("GitHub_RepositoryNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка существующего файла в репозитории....
        /// </summary>
        internal static string GitHub_Stage_CheckExistingFile {
            get {
                return ResourceManager.GetString("GitHub_Stage_CheckExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключение к GitHub API....
        /// </summary>
        internal static string GitHub_Stage_ConnectingToAPI {
            get {
                return ResourceManager.GetString("GitHub_Stage_ConnectingToAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кодирование данных в Base64....
        /// </summary>
        internal static string GitHub_Stage_EncodeBase64 {
            get {
                return ResourceManager.GetString("GitHub_Stage_EncodeBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение архива с диска....
        /// </summary>
        internal static string GitHub_Stage_ReadFile {
            get {
                return ResourceManager.GetString("GitHub_Stage_ReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление файла на сервере (загрузка данных)....
        /// </summary>
        internal static string GitHub_Stage_UpdateFile {
            get {
                return ResourceManager.GetString("GitHub_Stage_UpdateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание нового файла на сервере (загрузка данных)....
        /// </summary>
        internal static string GitHub_Stage_UploadFile {
            get {
                return ResourceManager.GetString("GitHub_Stage_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка успешно завершена!.
        /// </summary>
        internal static string GitHub_Stage_UploadFileCompleted {
            get {
                return ResourceManager.GetString("GitHub_Stage_UploadFileCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Токен принадлежит пользователю.
        /// </summary>
        internal static string GitHub_TokenOwnerMismatch1 {
            get {
                return ResourceManager.GetString("GitHub_TokenOwnerMismatch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на но указан владелец.
        /// </summary>
        internal static string GitHub_TokenOwnerMismatch2 {
            get {
                return ResourceManager.GetString("GitHub_TokenOwnerMismatch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл существует. Загрузка отменена пользователем..
        /// </summary>
        internal static string GitHub_UploadCanceled {
            get {
                return ResourceManager.GetString("GitHub_UploadCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка успешно завершена!.
        /// </summary>
        internal static string GitHub_UploadSuccess {
            get {
                return ResourceManager.GetString("GitHub_UploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует карта цветов.
        /// </summary>
        internal static string Img_Convert_Error_NoPalette {
            get {
                return ResourceManager.GetString("Img_Convert_Error_NoPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение не должно быть монохромным и должно быть в формате 32bit.
        /// </summary>
        internal static string Img_Convert_Error_Not32bit {
            get {
                return ResourceManager.GetString("Img_Convert_Error_Not32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.
        /// </summary>
        internal static string Img_Convert_Error_NotSave1 {
            get {
                return ResourceManager.GetString("Img_Convert_Error_NotSave1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не был сохранен..
        /// </summary>
        internal static string Img_Convert_Error_NotSave2 {
            get {
                return ResourceManager.GetString("Img_Convert_Error_NotSave2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка обработки изображения.
        /// </summary>
        internal static string Img_Convert_Error_ReadErr {
            get {
                return ResourceManager.GetString("Img_Convert_Error_ReadErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытаться сохранить изображение?.
        /// </summary>
        internal static string Img_Convert_Error_SaveImg {
            get {
                return ResourceManager.GetString("Img_Convert_Error_SaveImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не верный формат исходного файла..
        /// </summary>
        internal static string Img_Convert_Error_WrongImg {
            get {
                return ResourceManager.GetString("Img_Convert_Error_WrongImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете добавлять анимацию на экран AOD..
        /// </summary>
        internal static string Message_AnimationAOD_Text {
            get {
                return ResourceManager.GetString("Message_AnimationAOD_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество изображений для отображения AQI должно быть равным 6..
        /// </summary>
        internal static string Message_AQI_Image_Count_Error {
            get {
                return ResourceManager.GetString("Message_AQI_Image_Count_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конвертация изображений в формат ARGB занимает больше времени..
        /// </summary>
        internal static string Message_ARGB_Line1 {
            get {
                return ResourceManager.GetString("Message_ARGB_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы точно хотите конвертировать изображения в формат ARGB?.
        /// </summary>
        internal static string Message_ARGB_Line2 {
            get {
                return ResourceManager.GetString("Message_ARGB_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка авторизации.
        /// </summary>
        internal static string Message_AuthorisationError_Caption {
            get {
                return ResourceManager.GetString("Message_AuthorisationError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановление.
        /// </summary>
        internal static string Message_AutoSave_Caption {
            get {
                return ResourceManager.GetString("Message_AutoSave_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нужно установить цвет в качестве основного фона..
        /// </summary>
        internal static string Message_BG_Not_Color {
            get {
                return ResourceManager.GetString("Message_BG_Not_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нужно установить изображение в качестве основного фона..
        /// </summary>
        internal static string Message_BG_Not_Image {
            get {
                return ResourceManager.GetString("Message_BG_Not_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка конфигурации.
        /// </summary>
        internal static string Message_ConfigurationError_Caption {
            get {
                return ResourceManager.GetString("Message_ConfigurationError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключено к симулятору!.
        /// </summary>
        internal static string Message_ConnectedSimulator_Text {
            get {
                return ResourceManager.GetString("Message_ConnectedSimulator_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый циферблат создан..
        /// </summary>
        internal static string Message_ConvertingCompleted_Text {
            get {
                return ResourceManager.GetString("Message_ConvertingCompleted_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Координаты скопированы.
        /// </summary>
        internal static string Message_CopyCoord {
            get {
                return ResourceManager.GetString("Message_CopyCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление.
        /// </summary>
        internal static string Message_Delet_Caption {
            get {
                return ResourceManager.GetString("Message_Delet_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите безвозвратно удалить файл &quot;.
        /// </summary>
        internal static string Message_Delet_Text1 {
            get {
                return ResourceManager.GetString("Message_Delet_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите безвозвратно удалить файлы:.
        /// </summary>
        internal static string Message_Delet_Text11 {
            get {
                return ResourceManager.GetString("Message_Delet_Text11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;?.
        /// </summary>
        internal static string Message_Delet_Text2 {
            get {
                return ResourceManager.GetString("Message_Delet_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ?.
        /// </summary>
        internal static string Message_Delet_Text21 {
            get {
                return ResourceManager.GetString("Message_Delet_Text21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить виджет?.
        /// </summary>
        internal static string Message_Delet_Widget {
            get {
                return ResourceManager.GetString("Message_Delet_Widget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно удалить существующий файл циферблата..
        /// </summary>
        internal static string Message_DontDelZip {
            get {
                return ResourceManager.GetString("Message_DontDelZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DXGI не поддерживается. Переключение на BitBlt..
        /// </summary>
        internal static string Message_DXGI_error_Text {
            get {
                return ResourceManager.GetString("Message_DXGI_error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете добавлять настраиваемые элементы на экран AOD..
        /// </summary>
        internal static string Message_EditableElementsAOD_Text {
            get {
                return ResourceManager.GetString("Message_EditableElementsAOD_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете добавлять настраиваемые стрелки на экран AOD..
        /// </summary>
        internal static string Message_EditablePointerAOD_Text {
            get {
                return ResourceManager.GetString("Message_EditablePointerAOD_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете добавить этот элемент на экран AOD..
        /// </summary>
        internal static string Message_ElementAOD_Text {
            get {
                return ResourceManager.GetString("Message_ElementAOD_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла не может быть пустым..
        /// </summary>
        internal static string Message_EmptyFileName {
            get {
                return ResourceManager.GetString("Message_EmptyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string Message_Error_Caption {
            get {
                return ResourceManager.GetString("Message_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка добавления шрифта .
        /// </summary>
        internal static string Message_Error_Font {
            get {
                return ResourceManager.GetString("Message_Error_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно открыть изображение:.
        /// </summary>
        internal static string Message_Error_Image_Text1 {
            get {
                return ResourceManager.GetString("Message_Error_Image_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на . У Вас нет прав на чтение файла, или изображение повреждено..
        /// </summary>
        internal static string Message_Error_Image_Text2 {
            get {
                return ResourceManager.GetString("Message_Error_Image_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка в виджете: .
        /// </summary>
        internal static string Message_Error_InWidget {
            get {
                return ResourceManager.GetString("Message_Error_InWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код зашифрован и не может быть распознан..
        /// </summary>
        internal static string Message_ErrorReadBin {
            get {
                return ResourceManager.GetString("Message_ErrorReadBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось распознать структуру циферблата..
        /// </summary>
        internal static string Message_ErrorReadJS {
            get {
                return ResourceManager.GetString("Message_ErrorReadJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти к файлу.
        /// </summary>
        internal static string Message_GoToFile_Caption {
            get {
                return ResourceManager.GetString("Message_GoToFile_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти к файлу?.
        /// </summary>
        internal static string Message_GoToFile_Text {
            get {
                return ResourceManager.GetString("Message_GoToFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество изображений для отображения пульса должно быть равным 6..
        /// </summary>
        internal static string Message_HR_Image_Count_Error {
            get {
                return ResourceManager.GetString("Message_HR_Image_Count_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение не должно быть монохромным и должно быть в формате 32bit.
        /// </summary>
        internal static string Message_Image32bit {
            get {
                return ResourceManager.GetString("Message_Image32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранные изображения выходят за диапазон имеющихся изображений..
        /// </summary>
        internal static string Message_ImageCount_Error {
            get {
                return ResourceManager.GetString("Message_ImageCount_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка конвертации изображения.
        /// </summary>
        internal static string Message_ImageFix_Error {
            get {
                return ResourceManager.GetString("Message_ImageFix_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string Message_Infirmation_Caption {
            get {
                return ResourceManager.GetString("Message_Infirmation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое имя файла.
        /// </summary>
        internal static string Message_InvalidFileName_Caption {
            get {
                return ResourceManager.GetString("Message_InvalidFileName_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла содержит подозрительные символы..
        /// </summary>
        internal static string Message_InvalidFileName_Text1 {
            get {
                return ResourceManager.GetString("Message_InvalidFileName_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Циферблат может не работать..
        /// </summary>
        internal static string Message_InvalidFileName_Text2 {
            get {
                return ResourceManager.GetString("Message_InvalidFileName_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильный JSON файл..
        /// </summary>
        internal static string Message_JsonError_Text {
            get {
                return ResourceManager.GetString("Message_JsonError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения JSON файла..
        /// </summary>
        internal static string Message_JsonReadError_Text {
            get {
                return ResourceManager.GetString("Message_JsonReadError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустите симулятор..
        /// </summary>
        internal static string Message_LaunchSimulator_Text {
            get {
                return ResourceManager.GetString("Message_LaunchSimulator_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найден файл с автосохранением. Вы хотите загрузить его?.
        /// </summary>
        internal static string Message_Load_AutoSave {
            get {
                return ResourceManager.GetString("Message_Load_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка настроек предпросмотра.
        /// </summary>
        internal static string Message_LoadPreviewStates_Caption {
            get {
                return ResourceManager.GetString("Message_LoadPreviewStates_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить имеющийся файл с набором параметров предпросмотра PreviewStates.json?.
        /// </summary>
        internal static string Message_LoadPreviewStates_Text {
            get {
                return ResourceManager.GetString("Message_LoadPreviewStates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдена конфигурация модели: .
        /// </summary>
        internal static string Message_ModelConfig_Error {
            get {
                return ResourceManager.GetString("Message_ModelConfig_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения конфигурации моделей.
        /// </summary>
        internal static string Message_ModelConfig_ReadError {
            get {
                return ResourceManager.GetString("Message_ModelConfig_ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот виджет не поддерживается выбранной моделью часов..
        /// </summary>
        internal static string Message_Old_OS {
            get {
                return ResourceManager.GetString("Message_Old_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Откройте проект с циферблатом..
        /// </summary>
        internal static string Message_OpenProject_Text {
            get {
                return ResourceManager.GetString("Message_OpenProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезагрузка.
        /// </summary>
        internal static string Message_Restart_Caption {
            get {
                return ResourceManager.GetString("Message_Restart_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для применения настроек необходимо перезагрузить программу..
        /// </summary>
        internal static string Message_Restart_Text1 {
            get {
                return ResourceManager.GetString("Message_Restart_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезапустить программу?.
        /// </summary>
        internal static string Message_Restart_Text2 {
            get {
                return ResourceManager.GetString("Message_Restart_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение проекта.
        /// </summary>
        internal static string Message_Save_JSON_Modified_Caption {
            get {
                return ResourceManager.GetString("Message_Save_JSON_Modified_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы хотите сохранить изменения в проекте &quot;.
        /// </summary>
        internal static string Message_Save_JSON_Modified_Text1 {
            get {
                return ResourceManager.GetString("Message_Save_JSON_Modified_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;?.
        /// </summary>
        internal static string Message_Save_JSON_Modified_Text2 {
            get {
                return ResourceManager.GetString("Message_Save_JSON_Modified_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий проект еще не сохранен. Вы хотите сохранить его?.
        /// </summary>
        internal static string Message_Save_new_JSON {
            get {
                return ResourceManager.GetString("Message_Save_new_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для сохранения предустановленных параметром установите хотя бы в одном поле &quot;Калории&quot; значение отличное от &quot;1234&quot;..
        /// </summary>
        internal static string Message_SaveOnly1234_Text {
            get {
                return ResourceManager.GetString("Message_SaveOnly1234_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Передача технической информации.
        /// </summary>
        internal static string Message_SendInfo_Caption {
            get {
                return ResourceManager.GetString("Message_SendInfo_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложение может отправлять на сервер техническую информацию о системе для сбора статистики и анализа совместимости:.
        /// </summary>
        internal static string Message_SendInfo_Text1 {
            get {
                return ResourceManager.GetString("Message_SendInfo_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на      • версия приложения.
        /// </summary>
        internal static string Message_SendInfo_Text2 {
            get {
                return ResourceManager.GetString("Message_SendInfo_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на      • версия Windows.
        /// </summary>
        internal static string Message_SendInfo_Text3 {
            get {
                return ResourceManager.GetString("Message_SendInfo_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на      • язык системы.
        /// </summary>
        internal static string Message_SendInfo_Text4 {
            get {
                return ResourceManager.GetString("Message_SendInfo_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на      • версии установленных компонентов .NET.
        /// </summary>
        internal static string Message_SendInfo_Text5 {
            get {
                return ResourceManager.GetString("Message_SendInfo_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Личные файлы и другие пользовательские данные не передаются..
        /// </summary>
        internal static string Message_SendInfo_Text6 {
            get {
                return ResourceManager.GetString("Message_SendInfo_Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы можете отключить передачу информации в настройках..
        /// </summary>
        internal static string Message_SendInfo_Text7 {
            get {
                return ResourceManager.GetString("Message_SendInfo_Text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не можете добавлять ярлыки на экран AOD..
        /// </summary>
        internal static string Message_ShortcutsAOD_Text {
            get {
                return ResourceManager.GetString("Message_ShortcutsAOD_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Симулятор отключен!.
        /// </summary>
        internal static string Message_Simulator_Disconnected_Text {
            get {
                return ResourceManager.GetString("Message_Simulator_Disconnected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Симулятор не подключен..
        /// </summary>
        internal static string Message_Simulator_NotConnected_Text {
            get {
                return ResourceManager.GetString("Message_Simulator_NotConnected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправлено успешно!.
        /// </summary>
        internal static string Message_Simulator_PushSuccess_Text {
            get {
                return ResourceManager.GetString("Message_Simulator_PushSuccess_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все еще соединяюсь... Пожалуйста, подождите..
        /// </summary>
        internal static string Message_Simulator_StillConnecting_Text {
            get {
                return ResourceManager.GetString("Message_Simulator_StillConnecting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Симулятор запущен..
        /// </summary>
        internal static string Message_SimulatorRuning_Text1 {
            get {
                return ResourceManager.GetString("Message_SimulatorRuning_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите модель и запустите эмулятор..
        /// </summary>
        internal static string Message_SimulatorRuning_Text2 {
            get {
                return ResourceManager.GetString("Message_SimulatorRuning_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество изображений для отображения тренировочной нагрузки должно быть равным 3..
        /// </summary>
        internal static string Message_TrainingLoad_Image_Count_Error {
            get {
                return ResourceManager.GetString("Message_TrainingLoad_Image_Count_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество изображений для отображения VO2Max должно быть равным 7..
        /// </summary>
        internal static string Message_VO2Max_Image_Count_Error {
            get {
                return ResourceManager.GetString("Message_VO2Max_Image_Count_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В этой папке уже существует папка с изображениями..
        /// </summary>
        internal static string Message_Warning_Assets_Exist1 {
            get {
                return ResourceManager.GetString("Message_Warning_Assets_Exist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рекомендуется создавать проект в отдельной папке..
        /// </summary>
        internal static string Message_Warning_Assets_Exist2 {
            get {
                return ResourceManager.GetString("Message_Warning_Assets_Exist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать проект в выбранной папке?.
        /// </summary>
        internal static string Message_Warning_Assets_Exist3 {
            get {
                return ResourceManager.GetString("Message_Warning_Assets_Exist3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        internal static string Message_Warning_Caption {
            get {
                return ResourceManager.GetString("Message_Warning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В проекте уже существует шрифт: .
        /// </summary>
        internal static string Message_Warning_Font_Exist1 {
            get {
                return ResourceManager.GetString("Message_Warning_Font_Exist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заменить его новым шрифтом?.
        /// </summary>
        internal static string Message_Warning_Font_Exist2 {
            get {
                return ResourceManager.GetString("Message_Warning_Font_Exist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В проекте уже существует изображение:.
        /// </summary>
        internal static string Message_Warning_Image_Exist1 {
            get {
                return ResourceManager.GetString("Message_Warning_Image_Exist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заменить его новым изображением?.
        /// </summary>
        internal static string Message_Warning_Image_Exist2 {
            get {
                return ResourceManager.GetString("Message_Warning_Image_Exist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string Message_Warning_Information {
            get {
                return ResourceManager.GetString("Message_Warning_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не верный API Key.
        /// </summary>
        internal static string Message_Warning_InvalidAPIKey_Text {
            get {
                return ResourceManager.GetString("Message_Warning_InvalidAPIKey_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В этой папке уже существует папка с JS файлами..
        /// </summary>
        internal static string Message_Warning_JS_Exist1 {
            get {
                return ResourceManager.GetString("Message_Warning_JS_Exist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл &quot;*.zpk&quot; уже существует. Перезаписать?.
        /// </summary>
        internal static string Message_Warning_OverwriteFile_Text {
            get {
                return ResourceManager.GetString("Message_Warning_OverwriteFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нельзя уменьшать номер версии циферблата..
        /// </summary>
        internal static string Message_Warning_Version_Lower {
            get {
                return ResourceManager.GetString("Message_Warning_Version_Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каталог .
        /// </summary>
        internal static string Message_WarningConverting_Text1 {
            get {
                return ResourceManager.GetString("Message_WarningConverting_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  уже существует. Заменить?.
        /// </summary>
        internal static string Message_WarningConverting_Text2 {
            get {
                return ResourceManager.GetString("Message_WarningConverting_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размеры изображения для Preview отличаются от стандартных..
        /// </summary>
        internal static string Message_WarningPreview_Text1 {
            get {
                return ResourceManager.GetString("Message_WarningPreview_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использовать существующие размеры?.
        /// </summary>
        internal static string Message_WarningPreview_Text2 {
            get {
                return ResourceManager.GetString("Message_WarningPreview_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такой виджет уже есть в циферблате..
        /// </summary>
        internal static string Message_Widget_Exists {
            get {
                return ResourceManager.GetString("Message_Widget_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указана неизвестная цветовая схема для модели:.
        /// </summary>
        internal static string Message_Wrong_ColorScheme {
            get {
                return ResourceManager.GetString("Message_Wrong_ColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат исходного изображения.
        /// </summary>
        internal static string Message_Wrong_Original_Image {
            get {
                return ResourceManager.GetString("Message_Wrong_Original_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось создать изображение предпросмотра. Возможно такое изображение уже имеется..
        /// </summary>
        internal static string Message_Wrong_Preview_Exists {
            get {
                return ResourceManager.GetString("Message_Wrong_Preview_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ZeppPlayer не найден по указанному пути..
        /// </summary>
        internal static string Message_ZeppPlayerNotFound {
            get {
                return ResourceManager.GetString("Message_ZeppPlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось найти запущенный ZeppPlayer..
        /// </summary>
        internal static string Message_ZeppPlayerTabNotFound1 {
            get {
                return ResourceManager.GetString("Message_ZeppPlayerTabNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Откройте в Chrome вкладку с ZeppPlayer или укажите координаты вручную..
        /// </summary>
        internal static string Message_ZeppPlayerTabNotFound2 {
            get {
                return ResourceManager.GetString("Message_ZeppPlayerTabNotFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Янв, Фев, Мрт, Апр, Май, Июн, Июл, Авг, Сен, Окт, Ноя, Дек.
        /// </summary>
        internal static string Month_StrArray {
            get {
                return ResourceManager.GetString("Month_StrArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фон .
        /// </summary>
        internal static string Tip_Background {
            get {
                return ResourceManager.GetString("Tip_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стрелки .
        /// </summary>
        internal static string Tip_Pointer {
            get {
                return ResourceManager.GetString("Tip_Pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фон %s.
        /// </summary>
        internal static string ToastBG {
            get {
                return ResourceManager.GetString("ToastBG", resourceCulture);
            }
        }
    }
}
